export type MinecraftEnhancement =
	'minecraft:aqua_affinity' |
	'minecraft:bane_of_arthropods' |
	'minecraft:blast_protection' |
	'minecraft:channeling' |
	'minecraft:binding_curse' |
	'minecraft:vanishing_curse' |
	'minecraft:depth_strider' |
	'minecraft:efficiency' |
	'minecraft:feather_falling' |
	'minecraft:fire_aspect' |
	'minecraft:fire_protection' |
	'minecraft:flame' |
	'minecraft:fortune' |
	'minecraft:frost_walker' |
	'minecraft:impaling' |
	'minecraft:infinity' |
	'minecraft:knockback' |
	'minecraft:looting' |
	'minecraft:loyalty' |
	'minecraft:luck_of_the_sea' |
	'minecraft:lure' |
	'minecraft:mending' |
	'minecraft:multishot' |
	'minecraft:piercing' |
	'minecraft:power' |
	'minecraft:projectile_protection' |
	'minecraft:protection' |
	'minecraft:punch' |
	'minecraft:quick_charge' |
	'minecraft:respiration' |
	'minecraft:riptide' |
	'minecraft:sharpness' |
	'minecraft:silk_touch' |
	'minecraft:smite' |
	'minecraft:soul_speed' |
	'minecraft:swift_sneak' |
	'minecraft:sweeping' |
	'minecraft:thorns' |
	'minecraft:unbreaking'