name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - id: cache
        name: Yarn Cache Dir
        run: echo "::set-output name=value::$(yarn cache dir)"

      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.cache.outputs.value }}
          key: yarn-cache-${{ github.sha }}
          restore-keys: yarn-cache-

      - name: Dispatch CI of Documentation
        uses: mvasigh/dispatch-action@main
        with:
          owner: insane-mc
          repo: docs
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          event_type: core-repo-push

      - name: Install
        run: yarn

      - name: Build
        run: yarn build
      
      - name: Copy Files to Bot Profile
        run: |
          mkdir dist/bot-profile
          cp README.md dist/bot-profile

      - name: Commit to Bot Profile
        uses: ./.github/actions/commit
        with:
          source: dist/bot-profile
          target-user: imc-bot
          target-repo: imc-bot
          access-token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Commit to 'datapack-hypixel-uhc'
        uses: ./.github/actions/commit
        with:
          source: dist/datapack-hypixel-uhc
          target-repo: datapack-hypixel-uhc
          access-token: ${{ secrets.GH_ACCESS_TOKEN }}
